#!/bin/bash -eu
# © 2017-present VoiceBase Inc. and Harald Rudell (https://www.voicebase.com) <support@voicebase.com>
# This source code is licensed under the MIT-style license found in the LICENSE in the root directory of this source tree.
DOWNLOAD_JS="node_modules/bower/lib/util/download.js"
if [ -f "$DOWNLOAD_JS" ]; then
  # diff --unified=1 node_modules/bower/lib/util/download.js download.js
  echo "Attempting to patch: ${DOWNLOAD_JS}…"
  patch --unified --forward --reject-file="/tmp/$USER" "$DOWNLOAD_JS" <<EOF
--- node_modules/bower/lib/util/download.js	2016-11-07 01:57:24.000000000 -0800
+++ download.js	2017-04-09 18:15:58.000000000 -0700
@@ -73,3 +73,4 @@
     var deferred = Q.defer();
-
+    if (url === 'https://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip')
+        url = 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/crypto-js/CryptoJS%20v3.1.2.zip'
     var contentLength;
EOF
  echo "ok"
else echo >&2 "Please run npm install bower, does not exist: $DOWNLOAD_JS"
fi
